### ISSUE TITLE
Investigate how to use external mocks

### ISSUE THREAD

**Issue by nrxus** [nrxus/faux#27]
It would be great if users of a library could use `faux` to export mocked versions of their public API. 

The problem is that items wrapped by `#[cfg(test)]` are intentionally not propagated through crates. Which means that any mocks created with the test flag are not lost when the crate is being used as a dependency. 

Once we figure out a workaround for this we should document it (perhaps a mini guide?) on how to do it.

**Comment by nrxus** [comment]
My first idea was for something like:

```TOML
# crate-a
[dependencies]
faux { version = "0.4", optional = true }

[features]
exposed-mocks = ["faux"]
```
