### ISSUE TITLE
Unsafe as a feature

### ISSUE THREAD

**Issue by nrxus** [nrxus/faux#4]
Writing unsafe on every mock is a bit annoying.

What if we added a feature called `unsafe` or `i-know-faux-is-unsafe-so-hush` that if turned on exposed the mocking methods as "safe" since the user has already opted-in the unsafety at the crate level.

**Comment by TedDriggs** [comment]
What if you added `reckless_then` as a "safe" version of `then` which just lies about the safety? You can gate the exposure of that method on a crate feature, and that way one crate turning it on won't cause other crates in the dependency graph to experience any behavior changes.

**Comment by nrxus** [comment]
Do you mind linking me documentation on how feature flags poison through cyclic dependencies? My google-fu is failing me.

**Comment by TedDriggs** [comment]
# crate A
```toml
[dependencies]
crate-b = { version = "0.1.0", features = ["foo"] }
crate-c = "1.1.0"
```

# crate C
```toml
[dependencies]
crate-b = { version = "0.1.0", features = ["baz"] }
```

At this point, crate A would see both `foo` and `baz` features enabled.
